In [1]:
import numpy as np
import pandas as pd

In [2]:
# pandas utf 8 pr work krta hai normal fromat me to ham log latin1 ka use ke gy
df = pd.read_csv('spam.csv',encoding= "latin1")  # isme ham latin1 is liye use kr rhe hai q ki data me emoji hai aur bhi bahot kuch hai

In [3]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

# 1 Data Cleaning

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [5]:
# drop null value
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [6]:
# rename the columns v1=taget , v2=text
df.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [7]:
df.sample(6)

     target                                               text
3178    ham  Does cinema plus drink appeal tomo? * Is a fr ...
1896    ham  I tot u outside cos darren say u come shopping...
3319    ham  Eh sorry leh... I din c ur msg. Not sad alread...
4794    ham  Saw Guys and Dolls last night with Patrick Swa...
2622    ham                                          Ok lor...
3991    ham  Dizzamn, aight I'll ask my suitemates when I g...

In [8]:
df.duplicated().sum()

np.int64(403)

In [9]:
#dublicate value hata rhe hai
df.drop_duplicates(keep='first')

     target                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [10]:
# value save kr rhe hai
df = df.drop_duplicates(keep='first')

In [11]:
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
# yaha ham target place 0 aur 1 kre gy with the help of label incoder
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [13]:
df['target'] =encoder.fit_transform(df['target']) # apply and save

In [14]:
df.head(4)

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...

In [15]:
df.to_csv("clean_data", index=False)